[package]
name = "mintbase-deps"
version = "0.1.0"
edition = "2018"
authors = ["evergreen-trading-systems <4870868+evergreen-trading-systems@users.noreply.github.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib","cdylib"]

[dependencies]
# near-indexer-test-framework={path="../../smart-fruit-dew/near-indexer-test-framework", features=["postgres"], optional=true}
clap = {version="3.0.0-beta.2",optional=true}
#mintbase-deps={path="../mintbase-deps", optional = true}
near-sdk = {git="https://github.com/evergreen-trading-systems/near-sdk-rs", optional = true}
serde = "1"
serde_json="1"
actix = {version="=0.11.0-beta.2",optional=true}
tokio = { version = "1.1", features = ["sync"], optional = true }
tracing = {git="https://github.com/tokio-rs/tracing", optional = true }
tracing-appender = {git="https://github.com/tokio-rs/tracing",optional=true}
tracing-subscriber = {git="https://github.com/tokio-rs/tracing", optional = true, features=["env-filter"] }
chrono = { version="0.4.19", optional = true }
bigdecimal = {version= "0.1.2" , optional = true}
openssl-probe = { version = "0.1.2" , optional = true}
uuid = { version = "0.8.2", features = ["serde", "v4"], optional = true }
dotenv = { version="0.15.0" , optional = true}
rayon = { version="1.5", optional = true }
hyper = {version="0.14.10",features=["full"], optional = true}
reqwest = {version="0.11.4",features = ["json"], optional = true}
tower = {version="0.4", features=["full"], optional = true}
tokio-postgres = {version="0.7.3",features=["with-serde_json-1","with-chrono-0_4"], optional = true}
futures = {version= "0.3.17", optional = true }
tokio-stream = {version= "0.1.7" , optional = true}

near-jsonrpc-client = {git="https://github.com/near/near-jsonrpc-client-rs",rev="dd7761b51e1775350be1782370aa22c0b0fe98d7",features=["sandbox"], optional=true}
near-client-primitives = { git = "https://github.com/near/nearcore", rev = "397a7a45b8efd3e4604374a4efabd567c03c0a19" ,optional=true}
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev = "397a7a45b8efd3e4604374a4efabd567c03c0a19" ,optional=true}
near-crypto = { git = "https://github.com/near/nearcore", rev = "397a7a45b8efd3e4604374a4efabd567c03c0a19" ,optional=true}
near-primitives = { git = "https://github.com/near/nearcore", rev = "397a7a45b8efd3e4604374a4efabd567c03c0a19" ,optional=true}
near-account-id = { git = "https://github.com/near/nearcore", rev="397a7a45b8efd3e4604374a4efabd567c03c0a19", optional=true}
# indexer
near-indexer = { git = "https://github.com/near/nearcore", rev="397a7a45b8efd3e4604374a4efabd567c03c0a19", optional=true}

[features]
store-wasm = ["wasm"]
factory-wasm = ["wasm"]
market-wasm = ["wasm"]
helper-wasm = ["wasm"]
test = ["clap","all"]
panic-test=[]
blockchain = ["near-indexer","near-jsonrpc-client","near-client-primitives",
    "near-jsonrpc-primitives","near-crypto","near-primitives",
    "near-account-id"]
all = [
    "tokio",
    "tracing-appender",
    "tracing",
    "tracing-subscriber",
    "chrono","bigdecimal","openssl-probe","uuid","dotenv","rayon",
    "hyper","reqwest","tower","tokio-postgres","futures","tokio-stream",
    "wasm","blockchain"
]
wasm = ["near-sdk"]
