[env]
ADDRESS="mintspace"
WATCH_ACCOUNTS="test"
INDEXER_CHAIN_ID = "local"
INDEXER_ACCOUNT_ID = "test.near"
INDEXER_TEST_SEED = "."
INDEXER_NUM_SHARDS = "1"
INDEXER_FAST = "0"
#INDEXER_GENESIS= ""
INDEXER_DOWNLOAD_GENESIS="false"
#INDEXER_DOWNLOAD_GENESIS_URL=""
INDEXER_DOWNLOAD_CONFIG="false"
#INDEXER_DOWNLOAD_CONFIG_URL=""
#INDEXER_BOOT_NODES=""
#INDEXER_MAX_GAS_BURNT_VIEW=""
NEAR_DIR="/root/.near"
POSTGRES_HOST="localhost"
POSTGRES_USER="postgres"
POSTGRES_DB_NAME="postgres"
POSTGRES_PASSWORD="abc123"
POSTGRES_PORT="5433"
NEAR_ROOT_PUBLIC="ed25519:5YY5cX3Qe7MWVLQ1xMS5rP6obRqGnDiQPCuVTAnD1ff4"
NEAR_ROOT_SECRET="ed25519:3isLDmD3WfPC8HJ9rjwDzZQKaZ3wtzRFmtCHc67S5fzWMtGjMtxJYxQibsmboC2pSJodgXRvgfRV2yxHjmxmz254"
POSTGRES="postgres://postgres:postgres@localhost"
[alias]     # command aliases
tra = "run -p mintbase-deps --bin transfer --release --features test,all"
cra = "run --bin create-required-accounts --release --features test,all"
dploy = "run --bin deploy --release --features test,all"
create-store = "run --bin call --release --features test"
rdploy = "run -p mintbase-deps --bin redeploy --release --features test,all"
wasm = "build --target wasm32-unknown-unknown --release"
doc-all = "doc -p mintbase-deps --release --features store-wasm --features factory-wasm --lib --no-deps --target-dir mintbase-core-docs"
factory-wasm = "rustc -p mintbase-deps --release --features factory-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/factory.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
store-wasm = "rustc -p mintbase-deps --release --features store-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/store.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
market-wasm = "rustc -p simple-market-contract --release --target wasm32-unknown-unknown --lib -- --emit link=wasm/market.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
helper-wasm = "rustc -p mintbase-deps --release --features helper-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/helper.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
test-deploy-contracts="test deploy_contracts -p mintbase-deps --lib --features test"
indexer = "rustc -p mintbase-near-indexer --release --bin mintbase-near-indexer -- --emit link=bin/indexer"
indexer-debug = "rustc -p mintbase-near-indexer --bin mintbase-near-indexer -- --emit link=bin/indexer"
