[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]

# instead of creating a new profile, this might be helpful:
# https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.wasm-release]
inherits = "release"   # base this on the default release profile
codegen-units = 1      # generate a single blob of machine/Wasm instructions
opt-level = "z"        # optimize for code size
lto = true             # compile at link time
debug = false          # no debug symbols/checks
panic = "abort"        # usually unwind, but that's extra overhead
overflow-checks = true # enable safety checks for arithmetic operations

[alias]
wasm = "rustc --target wasm32-unknown-unknown --profile wasm-release"
doc-all = "doc -p mintbase-deps --release --features store-wasm --features factory-wasm --lib --no-deps --target-dir mintbase-core-docs"
helper-wasm = "wasm -p helper -- --emit link=wasm/helper.wasm"
store-wasm = "wasm -p store -- --emit link=wasm/store.wasm"
factory-wasm = "wasm -p factory -- --emit link=wasm/factory.wasm"
market-wasm = "wasm -p simple-market-contract -- --emit link=wasm/market.wasm"
p2p_indexer = "rustc -p mintbase-near-indexer --release --bin p2p_indexer -- --emit link=bin/p2p_indexer"
mintlake = "rustc -p mintbase-near-indexer --release --bin mintlake -- --emit link=bin/mintlake"
#indexer = "rustc -p mintbase-near-indexer --release --bin mintbase-near-indexer -- --emit link=bin/indexer"
lint = "clippy -- -D warnings"
